### ISSUE TITLE
Getting list of channels managed by user

### ISSUE THREAD

**Issue by seejamescode** [ustream/api-docs#3]
For [this query](http://developers.ustream.tv/broadcasting-api/channel.html):
`https://api.ustream.tv/users/self/channels.json`

Where do you specify which user you are trying to get a list of channels of?

**Comment by tzetze** [comment]
Hi,

Sorry, I just noticed this question. This API endpoint will work only with
an OAuth2 access token provided. The token represents the user who allowed
the access to the API client.

**Comment by seejamescode** [comment]
Sweet, thanks. Is there a specification in the docs of which ones need the access token?

**Comment by tzetze** [comment]
Almost every API calls needs an access token. There's no indicator in the
docs
which flags these API calls. That's a good catch, we should improve our docs
with that info. But: it's ok to provide an access token with every API
call.

2016-05-06 17:14 GMT+02:00 James Y Rauhut notifications@github.com:
